version:
  server: "1.0.0"

base_url: "http://127.0.0.1:8080"
host: "127.0.0.1"
port: 8080

resource:
  mcp: "C:/Users/kimsehun/Desktop/Aircok/vibecraft/servers"

file:
  path: "./data_store"

log:
  path: "./vibecraft-app-python-log"
