version:
  server: "1.0.0"

base_url: "http://127.0.0.1:8000"
host: "127.0.0.1"
port: 8000

resource:
  mcp: "C:/Users/kimsehun/Desktop/Aircok/vibecraft/servers"

log:
  path: "./vibecraft-app-python-log"
