[project]
name = "vibecraft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "anthropic>=0.55.0",
    "fastmcp>=2.9.0",
    "mcp[cli]>=1.9.4",
    "pandas>=2.3.0",
    "python-dotenv>=1.1.1",
]
